openapi: 3.0.0

info:
  version: 1.0-SNAPSHOT
  title: WishList Service
  description: Wishlist Application

tags:
  - name: "WishList"

paths:
  /api/wishlists:
    get:
      summary: Get all Wish Lists
      tags:
        - "WishList"
      description: Show all Wish Lists
      operationId: getAllWishList
      responses:
        "200":
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WishList'

  /api/wishlists/{wishlistId}:
    delete:
      summary: Delete a Wish List
      parameters:
        - name: wishlistId
          in: path
          required: true
          description: Id of a Wish List
          schema:
            type : integer
            format: int64
            minimum: 1
      tags:
        - "WishList"
      description: Delete a Wish List by Wish List's id
      operationId: deleteWishList
      responses:
        "200":
          description: Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
components:
  schemas:
    WishList:
      description: This is Wish List model
      type: object
      properties:
        title:
          description: Title of the Wish List
          type: string
        wishlistDate:
          description: Date when Wish List was created
          type: string
        wishlistDescription:
          description: Description of the Wish List
          type: string
        privacyType:
          description: Privacy of Wish List
          type: string
        wishListType:
          description: Type of Wish List
          type: string